{{- if .Values.realmImport.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-realm-import
data:
  import-file.json: |-
{{ .Values.realmImport.content | indent 4 }}
{{- end -}}
